### ISSUE TITLE
CodeContracts 

### ISSUE THREAD

**Issue by jogibear9988** [llehn/Contracts4Net#1]
If you read https://blogs.msdn.microsoft.com/dotnet/2016/08/24/whats-new-in-csharp-7-0/ (comments) and https://github.com/Microsoft/CodeContracts/issues/409 -> CodeContracts seem to be dead

**Comment by llehn** [comment]
yes exactly thats why we need something else :D

**Comment by jogibear9988** [comment]
I'm not sure if we should name it CodeContracts. I think the MS CodeContracts rewrite the Assembly, will you do also? So maybe a new Name is better?
